### ISSUE TITLE
Multiline lore support

### ISSUE THREAD

**Issue by VozikCZE** [Wolfieheart/ArmorStandEditor#217]
### Is your feature request related to a problem?

Now I can have only one line of lore in GUI menu, which is very limiting for descriptions.

### Describe the solution you'd like.

Remake the language files to something like this:

```YAML
baseplate:
  msg: BasePlate
  description:
    msg: 
    - "Description line 1"
    - "Description line 2"
```

### Describe alternatives you've considered.

It can be also realised by support of "\n". 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.
