### ISSUE TITLE
updated lang zh_CN.yml

### ISSUE THREAD

**Issue by SeemWind** [Wolfieheart/ArmorStandEditor#525]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

```
#信息
setmode:
  msg: 设置对象更改为 <x> , 点击盔甲架开始调整
  head: 头部
  body: 躯体
  leftleg: 左腿
  rightleg: 右腿
  leftarm: 左臂
  rightarm: 右臂
  equipment: 装备
  showarms: 手臂显隐切换
  invisible: 显隐切换
  size: 大小切换
  disableslots: 物品栏切换
  vulnerability: 可破坏状态切换
  gravity: 重力切换
  baseplate: 底座切换
  placement: 位置
  rotate: 旋转
  copy: 复制
  paste: 粘贴
  reset: 重设角度
setaxis:
  msg: 设置坐标为 <x>
  x: X
  y: Y
  z: Z
setslot:
  msg: 设定存档槽位 <x>
setadj:
  msg: 设置调整模式 <x>
  coarse: 粗调
  fine: 微调
setgravity:
  msg: 重力 <x>
  on: 开启
  off: 关闭
nomode:
  msg: 请先点击空气选择设定模式!
nomodeif:
  msg: 请先点击空气选择设定模式!
copied:
  msg: 盔甲架状态已保存于 <x>
pasted:
  msg: 已从 <x> 粘贴盔甲架状态
target:
  msg: 目标盔甲架已锁定
notarget:
  msg: 目标 <x> 已解锁
  armorstand: 盔甲架
  itemframe: 物品展示框
frametarget:
  msg: 目标物品展示框已锁定
doubletarget:
  msg: 请看向盔甲架或物品展示框, 不要同时看向多个!
reloaded:
  msg: 配置文件已重新加载
nodoubletarget:
  msg: 请在切换副手前看向盔甲架或物品展示框!
toggleinvulnerability:
  msg: 盔甲架可破坏状态已更改为 <x>
  true: 不可破坏
  false: 可破坏
help:
  msg: "1. 手持编辑工具(<x>).

      2. 对着盔甲架“左键或右键”来打开菜单.

      3. 选择标记的菜单选项.

      4. 使用编辑工具对着盔甲架“左键”以应用那些选项.

      5. 右键单击可反方向编辑!"
helptips:
  msg: "小提示:

  1. 当有别的盔甲架挡着你要编辑的盔甲架时, 你可以拿着编辑工具按下“切换副手物品”键(默认为 F)来标记你想要编辑的盔甲架.

  2. 你可以将“命名牌(NameTags)”用于盔甲架. 更重要的是, 你可以使用“&样式代码”标签赋予命名牌更多色彩.

  3. 你可以在手持编辑工具时使用“潜行(Shift) + 鼠标滚轮”来快速更改要修改的轴而不需要打开菜单."
helpurl:
  msg: "更多信息: https://github.com/RypoFalem/ArmorStandEditor/wiki"
helpdiscord:
  msg: "或加入我们的讨论区: https://discord.gg/3BbJKWpTCj"
give:
  msg: 玩家已获取自定义模型数据的物品
playerhead:
  msg: 玩家头颅已获取
noplayerhead:
  msg: 请先在配置文件中开启获取玩家头颅功能
playerheaderror:
  msg: 无法获取玩家头颅
notincorrectworld:
  msg: 对不起，您没有在正确的世界中使用盔甲架编辑器。
unabledestroycreative:
  msg: 无法在创造模式中摧毁这个不可破坏的盔甲架。
stats:
  msg: 以下是盔甲架的统计数据。

#警告
cantedit:
  msg: 对不起, 你无法在这里编辑盔甲架!
noperm:
  msg: 你没有权限这样做!
nopermoption:
  msg: 您无权使用 <x> 该选项！
  basic: 普通盔甲架
  showarms: 展示武器
  armorstandvisibility: 盔甲架可见性
  baseplate: 设置底板可见性
  gravity: 切换重力
  vulnerability: 切换脆弱性！
  itemframevisibility: 项目框架可见性
  size: 切换盔甲架大小
  disableslots: 切换装备锁
  paste: 粘贴盔甲架配置
  copy: 复制盔甲架配置
  reset: 重置盔甲架配置
  stats: 查看盔甲架统计数据
  armorstandglow: 切换盔甲架发光
norangestats:
  msg: 在运行此命令之前，请靠近盔甲架。
noslotnumcom:
  msg: 你必须选择一个物品栏!
noadjcom:
  msg: 你必须选择一个调整模式(粗调/微调)!
noaxiscom:
  msg: 你必须选择一个坐标轴!
nomodecom:
  msg: 你必须选择一个部位!
noreloadcom:
  msg: 你没有权限运行重载命令!
nogive:
  msg: 你没有权限运行给予命令!

#菜单标题
mainmenutitle:
  msg: 盔甲架编辑器
equiptitle:
  msg: 盔甲架装备

#图标
xaxis:
  msg: X 轴
  description:
    msg: 调整 X 轴位置
vulnerability:
  msg: 切换不可破坏
  description:
    msg: 切换一个盔甲架的不可破坏状态
yaxis:
  msg: Y 轴
  description:
    msg: 调整 Y 轴位置
zaxis:
  msg: Z 轴
  description:
    msg: 调整 Z 轴位置
coarseadj:
  msg: 粗略调整
  description:
    msg: 调整幅度较大
fineadj:
  msg: 精细调整
  description:
    msg: 调整幅度较小
head:
  msg: 头部
  description:
    msg: 旋转头部
body:
  msg: 躯体
  description:
    msg: 旋转躯体
leftleg:
  msg: 左腿
  description:
    msg: 旋转左腿
rightleg:
  msg: 右腿
  description:
    msg: 旋转右腿
leftarm:
  msg: 左臂
  description:
    msg: 旋转左臂
rightarm:
  msg: 右臂
  description:
    msg: 旋转右臂
equipment:
  msg: 装备
  description:
    msg: 编辑装备
showarms:
  msg: 显示手臂
  description:
    msg: 切换是否显示手臂
invisible:
  msg: 盔甲架显隐切换
  description: 
    msg: 显示/隐形盔甲架
size:
  msg: 大小
  description:
    msg: 调整大小
disableslots:
  msg: 禁用盔甲槽操作
  description:
    msg: 开启或关闭装备锁定
gravity:
  msg: 重力
  description:
    msg: 开启或关闭盔甲架重力
baseplate:
  msg: 底座
  description:
    msg: 显示关闭底座
placement:
  msg: 位置
  description:
    msg: 移动盔甲架的位置
rotate:
  msg: 旋转
  description:
    msg: 旋转盔甲架位置
copy:
  msg: 复制
  description:
    msg: 复制盔甲架设定
paste:
  msg: 粘贴
  description:
    msg: 粘贴盔甲架设定
copyslot:
  msg: 设定存档<x>
  description:
    msg: 选择保存盔甲架设定的一个存档位
reset:
  msg: 重设角度
  description:
    msg: 重设各个部件的角度
helpgui:
  msg: 我需要帮助!
  description:
    msg: 点击获得帮助!
itemframevisible:
  msg: 物品展示框显隐切换
  description:
    msg: 显示/隐形物品展示框
blankslot:
  msg: 这里什么都没有
  description:
    msg: 只是一个占位符项。单击“我”不会执行任何操作。
playerheadmenu:
  msg: 玩家头
  description:
    msg: 请使用 /ase playerhead <name>
armorstandglow:
  msg: 切换盔甲架发光
  description:
    msg: 转动盔甲架发光打开或关闭。

#图标 (装备)
disabled:
  msg: 关闭
equipslot:
  msg: <x> 槽
  description:
    msg: 将你的 <x> 放置到下面的格子
    helm: 头盔
    chest: 胸甲
    pants: 护膝
    boots: 靴子
    rhand: 右手
    lhand: 左手
  helm: 头盔
  chest: 胸甲
  pants: 护膝
  boots: 靴子
  rhand: 右手
  lhand: 左手

#all things related to Presets
presetmenu:
  msg: 预设姿势
  description:
    msg: 使用预设姿势盔甲架[将打开另一个菜单]

#icons (Preset Menu)
sitting:
  msg: 坐
  description:
    msg: 是时候坐下来放松一下了。
waving:
  msg: 挥舞
  description:
    msg: 嘿，过来！
greeting 1:
  msg: 问候语 1
  description:
    msg: 你好，我是你们的盔甲架。
greeting 2:
  msg: 问候语 2
  description:
    msg: 哦，嘿，我是你的盔甲架。
archer:
  msg: 射手
  description:
    msg: 小心，你的装甲架即将向你开枪：O
dancing:
  msg: 婆娑
  description:
    msg: 嘿，你想跳舞吗？
cheers:
  msg: 干杯
  description:
    msg: 让我们为此干杯！
hanging:
  msg: 绞刑
  description:
    msg: 是时候像我们的生命一样挂在这座山上了。
present:
  msg: 礼物
  description:
    msg: 你的盔甲架有礼物给你 <3
fishing:
  msg: 钓鱼
  description:
    msg: 是时候去钓鱼了

#Help for Presets
backtomenu:
  msg: 返回菜单
  description:
    msg: 单击“我”返回主菜单
howtopreset:
  msg: 如何
  description:
    msg: 有关如何使用预设的简短消息。
howtopresetmsg:
  msg: "1. 将编辑工具握在主手中
  
  2. 打开预设模式处于活动状态的菜单。
  
  3. 选择要选择的盔甲架预设之一。
  
  4. 选择后，您的菜单将关闭并应用您选择的预设。"

```

### Describe alternatives you've considered.

no

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.
